plugins {
    id 'com.android.application'
}

android {
    namespace 'com.apluse.restore'
    compileSdkVersion 33

    defaultConfig {
        applicationId "com.apluse.restore"
        minSdk 21
        targetSdk 33
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
